### ISSUE TITLE
Petition page

### ISSUE THREAD

**Issue by glotato** [politicalrev/wp.thepoliticalrev.org#10]
Amanda, Aidan and I Need to be able to create our own petition pages or be able to throw up immediately

**Comment by innovativedmm** [comment]
**Petition Form: Example using -speakout- plugin** 
[Petition: Moving Forward with Ellison](https://political-revolution.com/move-forward-with-keith-ellison/)
------
<img width="484" alt="screen shot 2016-12-22 at 5 59 56 am" src="https://cloud.githubusercontent.com/assets/3467080/21423632/1fb7bac0-c80c-11e6-927a-b48f80613578.png">

**Comment by Smona** [comment]
Yeah, looks like that petition form already works in the old theme. You can create those from the admin panel, right @innovativedmm ?
