### ISSUE TITLE
Font Usage Change

### ISSUE THREAD

**Issue by innovativedmm** [politicalrev/wp.thepoliticalrev.org#13]
Should be using only two fonts:
**Big John** 
**Work Sans**
_____
[Github Work Sans](https://weiweihuanghuang.github.io/Work-Sans/)
[Google Work Sans](https://fonts.google.com/specimen/Work+Sans) Using Light, Regular, Medium

**Comment by Smona** [comment]
Implemented Work Sans on commit 06097a16cad3c04f11b5d89b1a761b5fb59fd5c1. Headings with Big John aren't yet implemented.

@innovativedmm did we want to use big john on headings?

**Comment by innovativedmm** [comment]
Yes, I believe so. Just not all of them. Maybe #H1 only?

**Comment by Smona** [comment]
Big John added on https://github.com/politicalrev/wp.thepoliticalrev.org/commit/aa234efe00a62d8a9d58d80dfc82d46ef85d1af0

**Comment by innovativedmm** [comment]
Big John was added to "strong" bold, not H1.

**Comment by Smona** [comment]
I decided to go with strong tags because it gives us more flexibility. You think h1 is a better choice?
