### ISSUE TITLE
Stage Switcher

### ISSUE THREAD

**Issue by innovativedmm** [politicalrev/wp.thepoliticalrev.org#15]
[Stage Switcher](https://github.com/roots/wp-stage-switcher)

**Comment by Smona** [comment]
I will get this installed soon!

**Comment by Smona** [comment]
Why is this necessary? Can't you just change the url?

**Comment by innovativedmm** [comment]
I can achieve the same results by using Docker Hub Automated Build.

**Comment by Smona** [comment]
How so? Can you elaborate? Especially because we're using docker-compose, not just dockerfiles

**Comment by Smona** [comment]
Added to the new repo in https://github.com/politicalrev/political-revolution.com/commit/af69967a7179dd49cc201d4cb60607b602a5cee6
