### ISSUE TITLE
WP Admin for political-revolution.com broken

### ISSUE THREAD

**Issue by glotato** [politicalrev/wp.thepoliticalrev.org#18]
Hi Y'all - 

We need some things done by Jan 2nd. Can we use political-revolution.com to get a wp site up? Amanda can design the pages - she has mockups for a few things (I thought it was, but the log-in doesn't work anymore) 
Thanks 👍

**Comment by Smona** [comment]
Yes, that is currently a wordpress site. I was able to login just fine to the admin panel. Did you authenticate with the same slack channel as you registered with?

**Comment by Smona** [comment]
This might be related to #14

**Comment by innovativedmm** [comment]
@Smona 
This issue is resolved. We had to delete the plug-in that was causing the issue.
