### ISSUE TITLE
typography scss: reduce size and weights

### ISSUE THREAD

**Issue by innovativedmm** [politicalrev/wp.thepoliticalrev.org#19]
scss typography

**Reduce size and weight of body font**
$tiny-font-size: 10px;
$tiny-font-leading: 0.75;
$small-font-size: 14px;
$small-font-leading: 0.75;
$base-font-size: 18px;
$base-font-leading: 1;
$medium-font-size: 24px;
$medium-font-leading: 1.25;
$large-font-size: 32px;
$large-font-leading: 1.25;
$xlarge-font-size: 43px;
$xlarge-font-leading: 1.5;
_____
@mixin typeSize($size) {
 @if $size == "tiny" {
  @include adjust-font-size-to($tiny-font-size);
  @include adjust-leading-to($tiny-font-leading);
 }
 @if $size == "small" {
  @include adjust-font-size-to($small-font-size);
  @include adjust-leading-to($small-font-leading);
 }
 @if $size == "base" {
  @include adjust-font-size-to($base-font-size);
  @include adjust-leading-to($base-font-leading);
 }
 @if $size == "medium" {
  @include adjust-font-size-to($medium-font-size);
  @include adjust-leading-to($medium-font-leading);
 }
 @if $size == "large" {
  @include adjust-font-size-to($large-font-size);
  @include adjust-leading-to($large-font-leading);
 }
 @if $size == "xlarge" {
  @include adjust-font-size-to($xlarge-font-size);
  @include adjust-leading-to($xlarge-font-leading);
 }
}
_____
// Type weights
%t-ultrastrong {
 font-weight: 900;
}
%t-strong {
 font-weight: 700;
}
%t-regular {
 font-weight: 400;
}
%t-light {
 font-weight: 300;
}
%t-ultralight {
 font-weight: 200;
}
_____
// Type size variants 
%t-tiny {
 @include typeSize(tiny);
}
%t-small {
 @include typeSize(small);
}
%t-base {
 @include typeSize(base);
}
%t-medium {
 @include typeSize(medium);
}
%t-large {
 @include typeSize(large);
}
%t-xlarge {
 @include typeSize(xlarge);
}
.t-tiny {
 @include typeSize(tiny);
}
.t-small {
 @include typeSize(small);
}
.t-base {
 @include typeSize(base);
}
.t-medium {
 @include typeSize(medium);
}
.t-large {
 @include typeSize(large);
}
.t-xlarge {
 @include typeSize(xlarge);
}
// Type — headings
#{headings(4)} {
 margin: 0;
}
h1 {
 @extend %t-xlarge;
}
h2 {
 @extend %t-large;
}
h3 {
 @extend %t-medium;
}
h4 {
 @extend %t-base;
_____
_Creating the placeholders gives us the possibility to use the @extend directive on any of our elements and save valuable lines of CSS and reduce repetition and redundancy. For example, if we have a paragraph in the header that need to look like an h2 we simply write the following:_
header > p {
  @extend %t-large
}
_____
Modular scale
10 px — tiny font size
14 px — small font size
18 px— base font size
24 px— medium font size
32 px— large font size
43 px — xlarge font size

**Let’s move the scale to set the base font size to 14px for small screens. 
We take down the font size of every (except tiny, which is tiny enough) for a modular scale level. Small becomes tiny, base becomes small etc.**
10 px — tiny font size
10 px — small font size
14 px— base font size
18 px— medium font size
24 px— large font size
32 px — xlarge font size
_____
**mixin**
@mixin responsiveTypeSize($size) {
 @if $size == "tiny" {
  @include adjust-font-size-to($tiny-font-size, $tiny-font-leading);
 }
 @if $size == "small" {
  @include adjust-font-size-to($tiny-font-size, $tiny-font-leading);
  @include breakpoint($small-screen-width) {
   @include adjust-font-size-to($tiny-font-size, $tiny-font-leading);
  }
 }
 @if $size == "base" {
  @include adjust-font-size-to($small-font-size, $small-font-leading);
  @include breakpoint($small-screen-width) {
   @include adjust-font-size-to($base-font-size, $base-font-leading);
  }
 }
 @if $size == "medium" {
  @include adjust-font-size-to($base-font-size, $base-font-leading);
  @include breakpoint($small-screen-width) {
   @include adjust-font-size-to($medium-font-size, $medium-font-leading);
  }
 }
 @if $size == "large" {
  @include adjust-font-size-to($medium-font-size, $medium-font-leading);
  @include breakpoint($small-screen-width) {
   @include adjust-font-size-to($large-font-size, $large-font-leading);
  }
 }
 @if $size == "xlarge" {
  @include adjust-font-size-to($large-font-size, $large-font-leading);
  @include breakpoint($small-screen-width) {
   @include adjust-font-size-to($xlarge-font-size, $xlarge-font-leading);
  }
 }
}

**Comment by Smona** [comment]
Can you rewrite this as a description of the features you want as well? Makes it easier to grok what you want. Basically you want the new email form, the font changes (which we already made) and a slightly transparent header, correct?

I like the header idea, I'll play around with that.

**Comment by Smona** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Checklist Of URGENT NEEDS HOMEPAGE.](https://trello.com/c/jcz4QCHS/191-checklist-of-urgent-needs-homepage)

**Comment by Smona** [comment]
Expanded on in #23
