### ISSUE TITLE
No class assigned to header text over-ride.

### ISSUE THREAD

**Issue by innovativedmm** [politicalrev/wp.thepoliticalrev.org#24]
Can't change header styles, there is no class assign, perhaps on your local install?
_____
<style type="text/css">element.style{}.page .page-header>h1{text-align:center;font-size:2.5em;margin-left:2rem;margin-right:2rem;margin-top:.5em;}</style>
 
 _____
<style type="text/css">element.style{font-size:60px;}.page .page-header>h1{text-align:center;font-size:1.5em;margin-left:2rem;margin-right:2rem;margin-top:.5em;}h1{font-size:2.5em;}h1,h2,h3,h4,h5,h6{color:#fff;font-weight:100;line-height:1.3;margin:0 0 .5em;}</style>

**Comment by Smona** [comment]
I'm sorry, I can't understand what you're asking for here. What do you want to override?

Btw you can use markdown to format the code so it's easier to read.

**Comment by Smona** [comment]
Clarified in #27
