### ISSUE TITLE
Get Started button from /fight to /volunteer

### ISSUE THREAD

**Issue by innovativedmm** [politicalrev/wp.thepoliticalrev.org#26]
Should lead to the Volunteer page.

`<a href="{{ site.baseurl }}/fight" class="button next">Get Started</a>`

Change ^ to **/volunteer**

**Comment by Smona** [comment]
Also need to change `{{ site.baseurl }}` to the WordPress equivalent

**Comment by Smona** [comment]
Made the front page text editable from wordpress admin in commit 68e76cf85ec1c0887df121c6e17eaebeb7cff16c and updated the link!
