### ISSUE TITLE
Local docker development environment difficult to set up

### ISSUE THREAD

**Issue by Smona** [politicalrev/wp.thepoliticalrev.org#28]
This may largely be a shortcoming in our developer documentation but many are having trouble getting started. Issues I'm aware of: 

- [x] local environment does not include a database which resembles production environment 
- [x] less technically knowledgeable volunteers are having trouble getting node/docker installed correctly 
- [x] Add links to step-by-step installation guides for dependencies, such as Xcode or homebrew

Please comment with any other difficulties

**Comment by HaydenSD** [comment]
I tried to get it up and running and `docker-compose` wouldn't work. I can grab the complete log if you want.

**Comment by Smona** [comment]
@HaydenSD yes please

**Comment by HaydenSD** [comment]
@Smona will do when I get home.

**Comment by KorvinSzanto** [comment]
> local environment does not include a database which resembles production environment

not sure how really to help with this, I'm sure wordpress has something

> less technically knowledgeable volunteers are having trouble getting node/docker installed correctly

Docker shouldn't really be necessary, you only need a webroot and a mysql installation. I think less advanced users should use something simple like WAMP or MAMP, this is wordpress after all. I'm personally using laravel valet with mysql installed by brew.

In terms of node, sass aint gonna compile itself. As long as the installation is documented, I don't think we can really help this without setting up a remote stage a developer could use.

> Add links to step-by-step installation guides for dependencies, such as Xcode or homebrew

Definitely having links to guides for setting up webroots and mysql databases would be good.

**Comment by Smona** [comment]
Documentation might be better broken up into:

1. Get the code (clone, link to basic git tutorial)
2. Install a local server environment (either get docker and use our custom compose setup or use mamp or vagrant with link to guides for each)
3. Install our build tools (node, Bower, gulp. Include installation guide for Mac (homebrew) and windows and specific note about fixing npm permissions)
4. Set up your local database (include switching to our theme or how to sync to our remote once we figure that out)
5. Link to contributing.md (which also needs an update. Oof)

**Comment by Smona** [comment]
@KorvinSzanto @HaydenSD please try setting up a local environment using https://github.com/politicalrev/political-revolution.com

Think I've solved this problem but need to test it.
