### ISSUE TITLE
Re-add bootstrap files to theme

### ISSUE THREAD

**Issue by Smona** [politicalrev/wp.thepoliticalrev.org#29]
These got deleted at some point, but we want to use bootstrap going forward for ongoing ease of development. This should be fixed by looking at the code included with the sage starter theme and adding them back to our repo

**Comment by HaydenSD** [comment]
Do we want to just add bootstrap to a css libraries folder and source it from there?

**Comment by Smona** [comment]
@HaydenSD With the way sage is set up, probably just easier to add with bower to undo https://github.com/politicalrev/wp.thepoliticalrev.org/commit/ffd5b290238cdbeac8e4c51fb87a0a8c4c47899a#commitcomment-20344185

**Comment by Smona** [comment]
Re-added in ba167eeaf4f586cbfdad0b26b45732ecd41c74ed. Bootstrap will be installed whenever you `bower install` or `npm start`
