### ISSUE TITLE
Enable Multisite?

### ISSUE THREAD

**Issue by austinheap** [politicalrev/wp.thepoliticalrev.org#3]
Since moving forward with Wordpress, we have an opporunity to enable Wordpress' multi-site mode: A feature of WordPress 3.0 and later versions that allows multiple virtual sites to share a single WordPress installation.

Other projects could simply start with a clean [Sage](https://github.com/roots/sage) theme and build what they need on top of Sage. We could then power the backend using the backend that powers the main site. From a technical standpoint, it's a decision that should be made early on to make it easier to handle down the road. More information is available [here](https://premium.wpmudev.org/blog/ultimate-guide-multisite/).

My personal thought is if we can enable _other_ projects along the way with the work we're doing, then it's an easy victory.

What does everyone think?

**Comment by Smona** [comment]
I'll ask #writing if they want to administer the progressive times from the same Wordpress panel. I also see some potential with little TPR offshoot pages being managed centrally.

If it's easier to enable multisite at the beginning and it has no drawbacks, I say _go for it_.

**Comment by austinheap** [comment]
Cool, I'll get that setup in the next day or two.

**Comment by KorvinSzanto** [comment]
The thing with multisite is that you can't really go back once it's been enabled for a while (says 5 year old knowledge) so it might be better to take this one slow. I'm of the mind that multiple smaller codebases are better than one monolith codebase powering everything.

**Comment by Smona** [comment]
True. We could also theoretically use the wp rest api to pull any data we need between sites. @austinheap are we good to say no to multisite? I agree with korvin's sentiments about keeping things as decoupled as possible
