### ISSUE TITLE
Feature - Navigation Links Disappear when User is on Current Page

### ISSUE THREAD

**Issue by meg-an** [politicalrev/wp.thepoliticalrev.org#31]
Hi all,

Navigating through the site, I have noticed that the link to whichever page you are on disappears from the main navigation bar. Even though I understand that feature is probably meant to reduce redundancy, this strikes me as a bad design choice for usability - the main navigation links should be consistent on every page - for the same reasons that the site navigation should appear in the same location on every page and maintain maintain the same style, type and colors (which it does). I think that if we are inviting all types of people to get involved, we should also keep all the main navigation links up on the main page to enable users to get used to the site and feel comfortable browsing it.

Once a user clicks into a site section, it’s a good idea to remind them where they are in the navigation bar (yes, even though the page has a clear heading) - perhaps by changing the color of the link to the current page and/or unlinking it.

If the reason for it is that there is not enough room to include all pages on the navigation bar, I might suggest shortening the "mission statement" link to simply "mission". 

- Megan

**Comment by tngreene** [comment]
@meg-an posted this before me. I also had the same thought. I've never seen any other website do that, and with good reason I think. Its very jarring and makes you have to re-scan and re-process the navigation bar.

Even the w3 commit thinks its a good
[idea](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G61) and a [bad one](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/F66)  to not have it consistent.

**Comment by Smona** [comment]
Thanks for the suggestion guys! This has been fixed in https://github.com/politicalrev/political-revolution.com/pull/3 in the new repo
